apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io
    targetRevision: 1.12.0
    helm:
      values: |
        ingress:
          enabled: true
          ingressClassName: traefik
          host: longhorn.k3s.haroldd.dev
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
          secureBackends: true
          tls: true
          tlsSecret: longhorn-tls
        longhornUI:
          replicas: 1
        persistence:
          defaultClass: false
        preUpgradeChecker:
          jobEnabled: false
# preUpgradeChecker.jobEnabled: false is required when using ArgoCD
  destination:
    name: "in-cluster"
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true