plugin: community.proxmox.proxmox

url: https://proxmox.haroldd.dev
user: terraform-prov@pve
token_id: terraform
token_secret: 2598a4db-5052-4b32-8126-e28bed69f4bf

validate_certs: true
want_proxmox_nodes_ansible_host: true
want_facts : true

compose:
  ansible_host: >
      (proxmox_ipconfig0.ip.split('/')[0])
      if (proxmox_vmtype == "qemu")
      else (proxmox_net0.ip.split('/')[0])
      if (proxmox_vmtype == "lxc")
      else inventory_hostname
keyed_groups:
  - key: proxmox_tags_parsed
    separator: ""
groups:
  ubuntu_vms: "'ubuntu' in (proxmox_tags_parsed|list)"
  k3s_workers: "'worker' in (proxmox_tags_parsed|list)"
  homelab_vms: "'homelab' in (proxmox_tags_parsed|list)"
