# SPDX-License-Identifier: MIT-0
---
adguard_home_version: "0.107.73"
adguard_home_service_name: adguard-home
# User and group under which AdGuard Home will run
adguard_home_user: adguard-home
adguard_home_group: adguard-home
adguard_home_data_dir: /var/lib/adguardhome # used as home directory

adguard_home_install_dir: /opt/adguardhome
adguard_home_binary_name: AdGuardHome
adguard_home_binary_path: "{{ adguard_home_install_dir }}/bin/{{ adguard_home_binary_name }}"
adguard_home_arch: amd64
adguard_home_config_dir: /etc/adguardhome
adguard_home_config_file: "{{ adguard_home_config_dir }}/AdGuardHome.yaml"
adguard_home_pid_file: /run/adguard-home/adguard-home.pid
adguard_home_allow_auto_update: false

adguard_home_service_extra_args: ""
adguard_home_service_capabilities:
  - CAP_NET_BIND_SERVICE
  - CAP_NET_RAW
